//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NTLauncher.rc
//
#define IDI_NTLAUNCHER      101
#define IDR_NOTIFYICON_MENU 102
#define IDD_SETTING_DIALOG  103
#define IDC_SETTING_DIALOG_CHECK_QQSCREENSHOT               1001
#define IDC_SETTING_DIALOG_CHECK_WECHATOCR                  1002
#define IDC_SETTING_DIALOG_CHECK_WECHATUTILITY              1003
#define IDC_SETTING_DIALOG_CHECK_AUTORUN                    1004
#define IDC_SETTING_DIALOG_CHECK_SCROLLVOLICE               1005
#define IDC_SETTING_DIALOG_CHECK_RUNTIP                     1006
#define IDC_SETTING_DIALOG_CHECK_RUNLAUNCHNTVIEWER          1007
#define IDC_SETTING_DIALOG_CHECK_OPENNTLAUNCHERDEBUGCONSOLE 1008
#define IDC_SETTING_DIALOG_CHECK_OPENNTVIEWERDEBUGCONSOLE   1009
#define IDC_SETTING_DIALOG_CHECK_KILLXPLUGLIN               1010
#define IDC_SETTING_DIALOG_CHECK_OCR                        1011
#define IDC_SETTING_DIALOG_CHECK_AUTOEXITCLEAR              1012
#define IDC_SETTING_DIALOG_EDIT_QQSCREENSHOT                1013
#define IDC_SETTING_DIALOG_BUTTON_AUTOOBTAINQQSCREENSHOT    1014
#define IDC_SETTING_DIALOG_EDIT_USRLIBPATH                  1015
#define IDC_SETTING_DIALOG_BUTTON_TENCENTOCR                1016
#define IDC_SETTING_DIALOG_BUTTON_WECHATXPLUGIN             1017
#define IDC_SETTING_DIALOG_EDIT_WECHATOCR                   1018
#define IDC_SETTING_DIALOG_EDIT_WECHATUTILITY               1019
#define IDC_SETTING_DIALOG_EDIT_PYTHONDIR                   1020
#define IDC_SETTING_DIALOG_BUTTON_AUTOOBTAINPYTHONDIR       1021
#define IDC_SETTING_DIALOG_EDIT_PLUGINDIR                   1022
#define IDC_SETTING_DIALOG_CHECK_PLUGIN                     1023
#define IDC_SETTING_DIALOG_EDIT_HOTKEYCTRL                  1024
#define IDC_SETTING_DIALOG_EDIT_HOTKEYALT                   1025
#define IDC_SETTING_DIALOG_EDIT_HOTKEYA                     1026
#define IDC_SETTING_DIALOG_CHECK_HOTKEY                     1027
#define IDC_SETTING_DIALOG_BUTTON_CLEARCACHE                1028
#define ID_NOTIFYICON_MENU_ABOUT          40001
#define ID_NOTIFYICON_MENU_SETTING        40002
#define ID_NOTIFYICON_MENU_ADDON_MANAGE   40003
#define ID_NOTIFYICON_MENU_SEARCH_PICTURE 40004
#define ID_NOTIFYICON_MENU_BATCH_OCR      40005
#define ID_NOTIFYICON_MENU_SCAN_QRCODE    40006
#define ID_NOTIFYICON_MENU_EXIT           40007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40008
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
